build-apk:
  image: ghcr.io/cirruslabs/flutter:stable
  stage: build
  script:
    - flutter pub get
    - flutter build apk --release --no-tree-shake-icons
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 7 days
  only:
    - main
